document.writeln("<table width=\"776\"  border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\">");
document.writeln("  <tr>");
document.writeln("      <td height=\"27\" background=\"\/images\/index1(1)_02.gif\"><div align=\"center\">");
document.writeln("        <table width=\"750\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
document.writeln("          <tr>");
document.writeln("            <td width=\"191\"><div align=\"center\" class=\"td\">");
document.writeln("                <SCRIPT language=JavaScript>");
document.writeln("<!--");
document.writeln("calendar1 = new Date();");
document.writeln("day = calendar1.getDay();");
document.writeln("month = calendar1.getMonth();");
document.writeln("date = calendar1.getDate();");
document.writeln("year = calendar1.getYear();");
document.writeln("if (year< 100) year = 1900 + year;");
document.writeln("cent = parseInt(year\/100);");
document.writeln("g = year % 19;");
document.writeln("k = parseInt((cent - 17)\/25);");
document.writeln("i = (cent - parseInt(cent\/4) - parseInt((cent - k)\/3) + 19*g + 15) % 30;");
document.writeln("i = i - parseInt(i\/28)*(1 - parseInt(i\/28)*parseInt(29\/(i+1))*parseInt((21-g)\/11));");
document.writeln("j = (year + parseInt(year\/4) + i + 2 - cent + parseInt(cent\/4)) % 7;");
document.writeln("l = i - j;");
document.writeln("emonth = 3 + parseInt((l + 40)\/44);");
document.writeln("edate = l + 28 - 31*parseInt((emonth\/4));");
document.writeln("emonth--;");
document.writeln("var dayname = new Array (\"星期日\", \"星期一\", \"星期二\", \"星期三\", \"星期四\", \"星期五\", \"星期六\");");
document.writeln("var monthname = new Array (\"1月\",\"2月\",\"3月\",\"4月\",\"5月\",\"6月\",\"7月\",\"8月\",\"9月\",\"10月\",\"11月\",\"12月\" );");
document.writeln("document.write(\"<span class=font9><font color=#000000>\"+year +\"年\");");
document.writeln("document.write(monthname[month]);");
document.writeln("document.write(date + \"日  \");");
document.writeln("document.write(dayname[day]+\" \"+\"<\/font><\/span>\");");
document.writeln("\/\/ January(1月份节日，以下同。)");
document.writeln("if ((month == 0) && (date == 1)) document.write(\"元旦\");");
document.writeln("if ((month == 4) && (date == 1)) document.write(\"国际劳动节\");");
document.writeln("if ((month == 4) && (date == 4)) document.write(\"青年节\");");
document.writeln("if ((month == 5) && (date == 1)) document.write(\"国际儿童节\");");
document.writeln("if ((month == 11) && (date == 25)) document.write(\"圣诞节\");");
document.writeln("document.write(\"<\/font>\");");
document.writeln("\/\/-->");
document.writeln("              <\/SCRIPT>");
document.writeln("                <SCRIPT>");
document.writeln("var SMDay= new Array (0,31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31);");
document.writeln("var a=0;");
document.writeln("var b,c,d;");
document.writeln("var today=new Date();");
document.writeln("yy=today.getYear();");
document.writeln("SMonth=today.getMonth()+1;");
document.writeln("SDay=today.getDate();");
document.writeln("weekday=today.getDay();");
document.writeln("if ((yy%4==0) & (yy%100!=0) | (yy%400==0)) SMDay[2] = 29;");
document.writeln("for (i=0;i<SMonth;i++)");
document.writeln("{");
document.writeln("a=SMDay[i]+a;");
document.writeln("}");
document.writeln("a=a+SDay;");
document.writeln("b=(7+a-weekday)%7;");
document.writeln("d=7-b;");
document.writeln("c=(a+d-weekday+7)\/7;");
document.writeln("document.write(\"<font color=#000000>\",\"第\",c,\"周\",\"<\/font>\");");
document.writeln("              <\/SCRIPT>");
document.writeln("            <\/div><\/td>");
document.writeln("            <td width=\"559\"><div align=\"center\" class=\"td\"><a href=\"http:\/\/www.8264.com\/index.htm\">首页<\/a> | <a href=\"http:\/\/shop.8264.com\" target=\"_blank\"><font color=red>商场<\/font><\/a> | <a href=\"http:\/\/www.8264.com\/news\/201.htm\">新闻<\/a> | <a href=\"http:\/\/www.8264.com\/pic\">图库<\/a> | <a href=\"http:\/\/www.8264.com\/web\/index.php\" target=\"_blank\">联盟<\/a> | <a href=\"http:\/\/www.8264.com\/zhuanti.php\">专题<\/a> | <a href=\"http:\/\/www.8264.com\/activity\/395.html\">活动<\/a> | <a href=\"http:\/\/bbs.8264.com\" target=\"_blank\"><font color=red>社区<\/font><\/a> | <a href=\"http:\/\/www.8264.com\/pic.php\">图文<\/a> | <a href=\"http:\/\/blog.8264.com\" target=\"_blank\">博客<\/a><\/div><\/td>");
document.writeln("          <\/tr>");
document.writeln("        <\/table>");
document.writeln("      <\/div><\/td>");
document.writeln("    <\/tr>");
document.writeln("    <tr>");
document.writeln("      <td><div align=\"center\">");
document.writeln("        <table width=\"776\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
document.writeln("          <tr>");
document.writeln("            <td width=\"215\" height=\"60\"><div align=\"left\"><a href=\"\/index.htm\"><img src=\"http:\/\/www.8264.com\/images\/logo1.gif\" width=\"205\" height=\"60\" border=\"0\"><\/a><\/div><\/td>");
document.writeln("            <td width=\"561\"><div align=\"center\">");
document.writeln("                <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
document.writeln("                  <tr>");
document.writeln("                    <td height=\"25\" background=\"\/images\/index1(1)_06.gif\"><div align=\"center\">");
document.writeln("                        <table width=\"100%\"  border=\"0\" cellspacing=\"0\" cellpadding=\"0\">");
document.writeln("                          <tr>");
document.writeln("                            <td width=\"16%\">");
document.writeln("                              <div align=\"right\"><a href=\"http:\/\/osm.8264.com\"><font color=\"red\">户外经理人DM<\/font><\/a><\/div><\/td>");
document.writeln("                            <td width=\"13%\"><div align=\"center\"><a href=\"http:\/\/retailer.8264.com\">户外店铺<\/a><\/div><\/td>");
document.writeln("                            <td width=\"14%\"><div align=\"center\" class=\"td\">");
document.writeln("                                <div align=\"center\"><a href=\"\/spark\/\">星火伙伴<\/a><\/div>");
document.writeln("                            <\/div><\/td>");
document.writeln("                            <td width=\"12%\"><div align=\"center\"><span class=\"td\"><a href=\"\/face2face\/index.htm\" target=\"_blank\">名家面对面<\/a><\/span><\/div><\/td>");
document.writeln("                            <td width=\"14%\"><div align=\"center\"><span class=\"td\"><a href=\"\/outdoornews\/489.html\" target=\"_blank\">行业报道<\/a><\/span><\/div><\/td>");
document.writeln("                            <td width=\"14%\"><div align=\"center\"><a href=\"http:\/\/job.8264.com\/\" target=\"_blank\">人力资源<\/a><\/div><\/td>");
document.writeln("                            <td width=\"20%\"><div align=\"center\"><a href=\"http:\/\/shop.8264.com\" target=\"_blank\"><img src=\"http:\/\/www.8264.com\/images\/index1_09.gif\" width=\"116\" height=\"18\" border=\"0\"><\/a><\/div><\/td>");
document.writeln("                          <\/tr>");
document.writeln("                        <\/table>");
document.writeln("                    <\/div><\/td>");
document.writeln("                  <\/tr>");
document.writeln("                  <tr>");
document.writeln("                    <td height=\"26\" background=\"\/images\/index1(1)_08.gif\"><div align=\"center\" class=\"td\"><a href=\"\/gear\/204.htm\">装备频道<\/a> - <a href=\"\/climb\/224.htm\">登山频道<\/a> - <a href=\"\/climbing\/232.htm\">攀岩频道<\/a> -  <a href=\"\/memo\/251.htm\">游记攻略<\/a> -  <a href=\"\/line\/243.htm\">经典线路<\/a> -  <a href=\"\/outdoor\/238.htm\">户外知识<\/a> - <a href=\"\/ski\/436.htm\">滑雪频道<\/a>  - <a href=\"\/paragliding\/389.htm\">滑翔<\/a><\/div><\/td>");
document.writeln("                  <\/tr>");
document.writeln("                <\/table>");
document.writeln("            <\/div><\/td>");
document.writeln("          <\/tr>");
document.writeln("        <\/table>");
document.writeln("      <\/div><\/td>");
document.writeln("    <\/tr>");
document.writeln("  <\/table>")